### ISSUE TITLE
Just Infos

### ISSUE THREAD

**Issue by TheseusFNK** [DCxDemo/CTR-tools#4]
Converting txt to .lng doesn't work. And how to convert modified .lev files from .obj back to .lev?

**Comment by TheseusFNK** [comment]
When i try to pack back a new modified .big file with big_splitter, i get an unknown md5, instead of the original one.

**Comment by DCxDemo** [comment]
the output BIG file differs due to different data padding approach. you can see the file size is different so in no way it can conicide the original md5, but as far as i tested it boots the game with that big just fine.

as of lev files you can't pack them back cause lots of data is still unknown. there are offsets all over and you can't generate it properly when you have no idea what a particular chunk means. also they split the whole mesh in chunks of 8 touching faces defined by 9 vertices, this algorithm should be somehow recreated for the import.

lng doesn't convert files due to ConvertTXT function being a dummy. i do remember i implemented this function, but for some reason i can't find any trace of it in my files. that's quite interesting.

**Comment by DCxDemo** [comment]
you can convert txt files back to lng now.
